export default [{
    title: 'PDV',
    route: 'PDV',
    visible: true,
    order: 10,
}, {
    title: 'Recepcion',
    route: 'Reception',
    visible: true,
    order: 10,
}, {
    title: 'Ventas',
    route: 'Sales',
    visible: true,
    order: 20,
}, {
    title: 'Precios',
    route: 'Prices',
    visible: true,
    order: 30,
}, {
    title: 'Control',
    route: 'Control',
    visible: true,
    order: 35,
}, {
    title: 'Inventario',
    route: 'Inventory',
    order: 40,
    visible: true,
}, {
    title: 'Ajustes',
    route: 'Adjustments',
    order: 50,
    visible: true,
}, {
    title: 'Delivery',
    route: 'DeliveryCategory',
    order: 60,
    visible: true,
}, {
    title: 'Salir',
    route: 'Onboarding/SignIn',
    order: 70,
    visible: true,
}]