export default [{
    title: 'PDV',
    route: 'PDV',
    visible: true,
    order: 10,
}, {
    title: 'Reposicion',
    route: 'Reposition',
    visible: true,
    order: 10,
}, {
    title: 'Ventas',
    route: 'Sales',
    visible: true,
    order: 20,
}, {
    title: 'Precios',
    route: 'Prices',
    visible: true,
    order: 30,
}, {
    title: 'Inventario',
    route: 'Inventory',
    order: 40,
    visible: true,
}, {
    title: 'Ajustes',
    route: 'Adjustments',
    order: 40,
    visible: true,
}, {
    title: 'Salir',
    route: 'Onboarding/SignIn',
    order: 40,
    visible: true,
}]